### ISSUE TITLE
. /ql/repo/vipGhost0_ql_help/help.sh 这个无法调用助力

### ISSUE THREAD

**Issue by Dhy827** [vipGhost0/ql_help#1]
task_before.sh 增加. /ql/repo/vipGhost0_ql_help/help.sh后无法调用互助码。
![QQ图片20210623011801](https://user-images.githubusercontent.com/55142573/122970944-0cb0e300-d3c1-11eb-8a98-f81ebda74007.png)
运行JD脚本提示如上图。

**Comment by vipGhost0** [comment]
这边测试了几种情况都是正常的，你的环境是啥？

**Comment by Dhy827** [comment]
设备是N1 刷的openwrt【. /ql/repo/vipGhost0_ql_help/help.sh】这条命令前面的标点是否也要填写上？

**Comment by vipGhost0** [comment]
要

**Comment by Dhy827** [comment]
大佬这个调用助力是否还受限于青龙的助力名额限制？
